name = "NestedPermutedDimsArrays"
uuid = "2c2a8ec4-3cfc-4276-aa3e-1307b4294e58"
version = "0.1.18"
authors = ["ITensor developers <support@itensor.org> and contributors"]

[workspace]
projects = ["benchmark", "dev", "docs", "examples", "test"]

[compat]
julia = "1.10"
