
[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
NestedPermutedDimsArrays = "2c2a8ec4-3cfc-4276-aa3e-1307b4294e58"

[compat]
Documenter = "1.8.1"
Literate = "2.20.1"
NestedPermutedDimsArrays = "0.1"
